spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${DATABASE_URL}
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
  application:
    name: backend
app:
  dadata:
    api-key: ${PUBLIC_KEY}
    secret-key: ${SECRET_KEY}
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui